export const fromLocation = [
  {
    id: 1,
    letter: "B",
    category: "B",
    name: "BOGOTA (BOG)",
    state: "Columbia",
    area: "Aeropuerto Int El Dorado",
  },
  {
    id: 2,
    category: "B",
    name: "BARRANQUILLA (BAQ)",
    state: "Columbia",
    area: "Aeropuerto Int El Dorado",
  },
  {
    id: 3,
    letter: "C",
    category: "C",
    name: "CALI (CLO)",
    state: "Columbia",
    area: "Aeropuerto Int El Dorado",
  },
  {
    id: 4,
    category: "C",
    name: "CARTAGENA (CTG)",
    state: "Columbia",
    area: "Aeropuerto Int Cortissoz",
  },
  {
    id: 5,
    letter: "M",
    category: "M",
    name: "MEDELLIN (MDE)",
    state: "Columbia",
    area: "Aeropuerto Int Cortissoz",
  },
  {
    id: 6,
    letter: "P",
    category: "P",
    name: "PEREIRA (PEI)",
    state: "Columbia",
    area: "Aeropuerto Int Cortissoz",
  },
  {
    id: 7,
    letter: "S",
    category: "S",
    name: "SAN ANDRES (ADZ)",
    state: "Columbia",
    area: "Aeropuerto Int Cortissoz",
  },
  {
    id: 8,
    category: "S",
    name: "SANTA MARTA (SMR)",
    state: "Columbia",
    area: "Aeropuerto Int Cortissoz",
  },
];
export const to = [
  {
    id: 1,
    show: [
      {
        id: 3,
        letter: "C",
        category: "C",
        name: "CALI (CLO)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 4,
        category: "C",
        name: "CARTAGENA (CTG)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 5,
        letter: "M",
        category: "M",
        name: "MEDELLIN (MDE)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 7,
        letter: "S",
        category: "S",
        name: "SAN ANDRES (ADZ)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 8,
        category: "S",
        name: "SANTA MARTA (SMR)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
    ],
  },
  {
    id: 2,
    show: [
      {
        id: 5,
        letter: "M",
        category: "M",
        name: "MEDELLIN (MDE)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
    ],
  },
  {
    id: 3,
    show: [
      {
        id: 1,
        letter: "B",
        category: "B",
        name: "BOGOTA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 4,
        letter: "C",
        category: "C",
        name: "CARTAGENA (CTG)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 5,
        letter: "M",
        category: "M",
        name: "MEDELLIN (MDE)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 7,
        letter: "S",
        category: "S",
        name: "SAN ANDRES (ADZ)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 8,
        category: "S",
        name: "SANTA MARTA (SMR)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
    ],
  },
  {
    id: 4,
    show: [
      {
        id: 1,
        letter: "B",
        category: "B",
        name: "BOGOTA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
    ],
  },
  {
    id: 5,
    show: [
      {
        id: 1,
        letter: "B",
        category: "B",
        name: "BOGOTA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 2,
        category: "B",
        name: "BARRANQUILLA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 3,
        letter: "C",
        category: "C",
        name: "CALI (CLO)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 4,
        category: "C",
        name: "CARTAGENA (CTG)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
      {
        id: 8,
        letter: "S",
        category: "S",
        name: "SANTA MARTA (SMR)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
    ],
  },
  {
    id: 6,
    show: [
      {
        id: 4,
        letter: "C",
        category: "C",
        name: "CARTAGENA (CTG)",
        state: "Columbia",
        area: "Aeropuerto Int Cortissoz",
      },
    ],
  },
  {
    id: 7,
    show: [
      {
        id: 1,
        letter: "B",
        category: "B",
        name: "BOGOTA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
      {
        id: 3,
        letter: "C",
        category: "C",
        name: "CALI (CLO)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
    ],
  },
  {
    id: 8,
    show: [
      {
        id: 1,
        letter: "B",
        category: "B",
        name: "BOGOTA (BOG)",
        state: "Columbia",
        area: "Aeropuerto Int El Dorado",
      },
    ],
  },
];
export const getFlightAmont = [
  {
    from: 1,
    to: 3,
    detail: [
      {
        days: [0, 1, 3, 5],
        depart_time: "6:50AM",
        return_time: "7:55AM",
        prices: 310.0,
      },
      {
        depart_time: "5:00 PM",
        return_time: "6:05 PM",
        days: [2, 4, 6],
        prices: 150.0,
      },
    ],
  },
  {
    from: 1,
    to: 4,
    days: "everyday",
    depart_time: "7:50 AM",
    return_time: "9:20 AM",
    prices: [446.0, 196.0, 154.0],
  },
  {
    from: 1,
    to: 4,
    days: "everyday",
    depart_time: "10:00 AM",
    return_time: "11:30 AM",
    prices: [446.0, 196.0, 154.0],
  },
  {
    from: 1,
    to: 5,
    days: "everyday",
    depart_time: "5:50 AM",
    return_time: "6:50 AM",
    prices: [270.0, 240.099, 190.0],
  },
  {
    from: 1,
    to: 5,
    days: "everyday",
    depart_time: "2:00 PM",
    return_time: "3:00 PM",
    prices: [270.0, 240.099, 190.0],
  },
  {
    from: 1,
    to: 5,
    days: "everyday",
    depart_time: "5:50 PM",
    return_time: "6:50 PM",
    prices: [270.0, 240.099, 190.0],
  },
  {
    from: 1,
    to: 5,
    days: ["TUESDAY", "THURSDAY", "SATURDAY"],
    depart_time: "8:10 PM",
    return_time: "9:10 PM",
    prices: [270.0, 240.099, 190.0],
  },
  {
    from: 1,
    to: 7,
    days: "everyday",
    depart_time: "10:00 AM",
    return_time: "12:10 PM",
    prices: [457.1, 227.1, 317.1],
  },
  {
    from: 1,
    to: 8,
    days: "everyday",
    depart_time: "3:50 PM",
    return_time: "5:20 PM",
    prices: [275.2, 157.2, 149.2],
  },
  {
    from: 1,
    to: 8,
    days: ["MONDAY", "WEDNESDAY", "FRIDAY", "SUNDAY"],
    depart_time: "9:00 PM",
    return_time: "10:30 PM",
    prices: [275.2, 157.2, 149.2],
  },
  {
    from: 3,
    to: 1,
    days: "everyday",
    depart_time: "8:25 PM",
    return_time: "9:30 AM",
    prices: [118.1, 134.1, 114.099],
  },
  {
    from: 3,
    to: 1,
    days: ["TUESDAY", "THURSDAY", "SATURDAY"],
    depart_time: "6:35 PM",
    return_time: "7:40 PM",
    prices: [118.1, 134.1, 114.099],
  },
  {
    from: 3,
    to: 4,
    days: ["MONDAY", "WEDNESDAY", "FRIDAY", "SUNDAY"],
    depart_time: "10:15 AM",
    return_time: "11:50 AM",
    prices: [199.9, 179.9, 249.9],
  },
  {
    from: 3,
    to: 5,
    days: "everyday",
    depart_time: "12:55 PM",
    return_time: "1:55 PM",
    prices: [127.0, 109.0, 149.0],
  },
  {
    from: 3,
    to: 7,
    days: "everyday",
    depart_time: "4:20 PM",
    return_time: "6:25 PM",
    prices: [196.3, 134.216, 266.3],
  },
  {
    from: 3,
    to: 8,
    days: "everyday",
    depart_time: "10:50 AM",
    return_time: "12:30 PM",
    prices: [201.9, 181.9, 161.9],
  },
  {
    from: 4,
    to: 1,
    depart_time: "11:00 AM",
  },
  {
    from: 4,
    to: 1,
    depart_time: "9:50 PM",
  },
  {
    from: 5,
    to: 2,
    depart_time: "6:30 AM",
  },
  {
    from: 5,
    to: 1,
    depart_time: "7:30 AM",
  },
  {
    from: 5,
    to: 1,
    depart_time: "3:30 PM",
  },
  {
    from: 5,
    to: 1,
    depart_time: "4:20 AM",
  },
  {
    from: 5,
    to: 1,
    depart_time: "10:50 AM",
  },
];
export const flightDetails = [
  {
    from: 1,
    to: 3,
    days1: [0, 1, 3, 5],
    adultoPrice:310.000,
    bebePrice:210.000,
    ninoPrice:150.000,
    price1: 310.000,
    days2: [2, 4, 6],
    price2: 310.000,
    flights: [
      {
        flightNo: "OL5130",
        departTime: "6:50 AM",
        timeDiff:"1Hora 5m",
        returnTime: "7:55 AM",
      },
      {
        flightNo: "OL5132",
        departTime: "5:00 PM",
        timeDiff:"1Hora 5m",
        returnTime: "6:05 PM",
      },
    ],
  },
  {
    from: 1,
    to: 4,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 446.0,
    days2: [],
    price2: 446.0,
    adultoPrice:446.000,
    bebePrice:196.000,
    ninoPrice:154.000,
    flights: [
      {
        flightNo: "OL5146",
        departTime: "7:50 AM",
        timeDiff:"1Hora 30m",
        returnTime: "9:20 AM",
      },
      {
        flightNo: "OL5140",
        departTime: "10:00 AM",
        timeDiff:"1Hora 30m",
        returnTime: "11:30 AM",
      },
    ],
  },
  {
    from: 1,
    to: 5,
    days1: [0, 1, 3, 5],
    price1: 270.000,
    days2: [2, 4, 6],
    price2: 270.000,
    adultoPrice:270.000,
    bebePrice:240.099,
    ninoPrice:190.000,
    flights: [
      {
        flightNo: "OL5110",
        departTime: "5:50 AM",
        timeDiff:"1Hora 0m",
        returnTime: "6:50 AM",
      },
      {
        flightNo: "OL5118",
        departTime: "2:00 PM",
        timeDiff:"1Hora 0m",
        returnTime: "3:00 PM",
      },
      {
        flightNo: "OL5113",
        departTime: "5:50 PM",
        timeDiff:"1Hora 0m",
        returnTime: "6:50 PM",
      },
      {
        flightNo: "OL5114",
        departTime: "8:10 PM",
        timeDiff:"1Hora 0m",
        returnTime: "9:10 PM",
      },
    ],
  },
  {
    from: 1,
    to: 7,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 457.100,
    days2: [],
    price2: 457.100,
    adultoPrice:457.100,
    bebePrice:227.100,
    ninoPrice:317.100,
    flights: [
      {
        flightNo: "OL5164",
        departTime: "10:00 AM",
        timeDiff:"2Hora 10m",
        returnTime: "12:10 PM",
      },
    ],
  },
  {
    from: 1,
    to: 8,
    days1: [0,1, 3, 5],
    price1: 275.2,
    days2: [2, 4, 6],
    price2: 275.2,
    adultoPrice:275.200,
    bebePrice:157.200,
    ninoPrice:149.200,
    flights: [
      {
        flightNo: "OL5158",
        departTime: "3:50 PM",
        timeDiff:"1Hora 30m",
        returnTime: "5:20 PM",
      },
      {
        flightNo: "OL5152",
        departTime: "9:00 AM",
        timeDiff:"1Hora 30m",
        returnTime: "10:30 AM",
      },
    ],
  },
  {
    from: 2,
    to: 5,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 117.7,
    days2: [],
    price2: 117.7,
    flights: [
      {
        flightNo: "OL5410",
        departTime: "6:30 AM",
        timeDiff:"1Hora 15m",
        returnTime: "7:45 AM",
      },
    ],
  },
  {
    from: 3,
    to: 1,
    days1: [0, 1, 3, 5],
    price1: 118.1,
    days2: [2, 4, 6],
    price2: 118.1,
    adultoPrice:118.100,
    bebePrice:134.100,
    ninoPrice:114.099,
    flights: [
      {
        flightNo: "OL5131",
        departTime: "8:25 AM",
        timeDiff:"1Hora 5m",
        returnTime: "9:30 AM",
      },
      {
        flightNo: "OL5133",
        departTime: "6:35PM",
        timeDiff:"1Hora 5m",
        returnTime: "7:40 PM",
      },
    ],
  },
  {
    from: 3,
    to: 4,
    days1: [1, 3, 5, 6],
    price1: 199.9,
    days2: [2, 4, 6],
    price2: 199.9,
    adultoPrice:199.900,
    bebePrice:179.900,
    ninoPrice:249.900,
    flights: [
      {
        flightNo: "OL5385",
        departTime: "10:15 AM",
        timeDiff:"1Hora 35m",
        returnTime: "11:50 AM",
      },
    ],
  },
  {
    from: 3,
    to: 5,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 127.0,
    days2: [],
    price2: 127.0,
    adultoPrice:127.000,
    bebePrice:109.000,
    ninoPrice:149.000,
    flights: [
      {
        flightNo: "OL5353",
        departTime: "12:55 PM",
        timeDiff:"1Hora 0m",
        returnTime: "1:55 PM",
      },
    ],
  },
  {
    from: 3,
    to: 7,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 196.3,
    days2: [],
    price2: 196.3,
    adultoPrice:196.300,
    bebePrice:216.300,
    ninoPrice:266.300,
    flights: [
      {
        flightNo: "OL3588",
        departTime: "4:20 PM",
        timeDiff:"2Hora 5m",
        returnTime: "6:25 PM",
      },
    ],
  },
  {
    from: 3,
    to: 8,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 201.9,
    days2: [],
    price2: 201.9,
    adultoPrice:201.900,
    bebePrice:181.900,
    ninoPrice:161.900,
    flights: [
      {
        flightNo: "OL5377",
        departTime: "10:50 AM",
        timeDiff:"1Hora 40m",
        returnTime: "12:30 PM",
      },
    ],
  },
  {
    from: 4,
    to: 1,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 244.0,
    days2: [],
    price2: 244.0,
    flights: [
      {
        flightNo: "OL5141",
        departTime: "11:00 AM",
        timeDiff:"1Hora 30m",
        returnTime: "12:30 PM",
      },
      {
        flightNo: "OL5147",
        departTime: "9:50 PM",
        timeDiff:"1Hora 30m",
        returnTime: "11:20 PM",
      },
    ],
  },
  {
    from: 5,
    to: 2,
    days1: [0, 1, 2, 3, 4, 5, 6],
    price1: 117.7,
    days2: [],
    price2: 117.7,
    flights: [
      {
        flightNo: "OL5410",
        departTime: "6:30 AM",
        timeDiff:"1Hora 15m",
        returnTime: "7:45 AM",
      },
    ],
  },
  {
    from: 5,
    to: 1,
    days1: [0, 1, 3, 5],
    price1: 190.0,
    days2: [2, 4, 6],
    price2: 190.0,
    flights: [
      {
        flightNo: "OL5111",
        departTime: "7:30 AM",
        timeDiff:"1Hora 0m",
        returnTime: "8:30 AM",
      },
      {
        flightNo: "OL5119",
        departTime: "3:30 PM",
        timeDiff:"1Hora 0m",
        returnTime: "4:30 PM",
      },
      {
        flightNo: "OL5112",
        departTime: "4:20 PM",
        timeDiff:"1Hora 0m",
        returnTime: "5:20 PM",
      },
      {
        flightNo: "OL5115",
        departTime: "9:40 PM",
        timeDiff:"1Hora 0m",
        returnTime: "10:40 PM",
      },
    ],
  },
  {
    from: 5,
    to: 3,
    days1: [1, 4, 6],
    price1: 189.6,
    days2: [0, 2, 3, 5],
    price2: 189.6,
    flights: [
      {
        flightNo: "OL5352",
        departTime: "2:40 PM",
        timeDiff:"1Hora 0m",
        returnTime: "3:40 PM",
      },
      {
        flightNo: "OL5354",
        departTime: "2:40 PM",
        timeDiff:"1Hora 0m",
        returnTime: "3:40 PM",
      },
    ],
  },
  {
    from: 5,
    to: 4,
    days1: [1, 4, 6],
    price1: 176.2,
    days2: [0, 2, 3, 5],
    price2: 176.2,
    flights: [
      {
        flightNo: "OL5322",
        departTime: "7:00 AM",
        timeDiff:"1Hora 10m",
        returnTime: "8:10 AM",
      },
      {
        flightNo: "OL5326",
        departTime: "7:20 PM",
        timeDiff:"1Hora 10m",
        returnTime: "8:30 PM",
      },
      {
        flightNo: "OL5324",
        departTime: "7:20 PM",
        timeDiff:"1Hora 10m",
        returnTime: "8:30 PM",
      },
    ],
  },
  {
    from: 5,
    to: 8,
    days1: [2, 3, 5, 6],
    price1: 149.199,
    days2: [0,1, 4],
    price2: 149.199,
    flights: [
      {
        flightNo: "OL5332",
        departTime: "6:55 AM",
        timeDiff:"1Hora 15m",
        returnTime: "8:10 AM",
      },
      {
        flightNo: "OL5336",
        departTime: "7:20PM",
        timeDiff:"1Hora 15m",
        returnTime: "8:35 PM",
      },
    ],
  },

  {
    from: 6,
    to: 4,
    days1: [2, 4, 6],
    price1: 231.0,
    days2: [0, 1, 3, 5],
    price2: 231.0,
    flights: [
      {
        flightNo: "OL5373",
        departTime: "7:00 PM",
        timeDiff:"1Hora 30m",
        returnTime: "8:30 PM",
      },
      {
        flightNo: "OL5371",
        departTime: "10:40 AM",
        timeDiff:"1Hora 30m",
        returnTime: "12:10 PM",
      },
    ],
  },
  {
    from: 7,
    to: 1,
    days1: [2, 4, 6],
    price1: 537.6,
    days2: [0, 1, 3, 5],
    price2: 537.6,
    flights: [
      {
        flightNo: "OL5165",
        departTime: "12:40 PM",
        timeDiff:"2Hora 10m",
        returnTime: "2:50 PM",
      },
      {
        flightNo: "OL5167",
        departTime: "5:30 PM",
        timeDiff:"2Hora 10m",
        returnTime: "7:40 PM",
      },
    ],
  },
  {
    from: 7,
    to: 3,
    days1: [1, 2, 4, 6],
    price1: 446.8,
    days2: [0, 3, 5],
    price2: 446.8,
    flights: [
      {
        flightNo: "OL5389",
        departTime: "10:20 AM",
        timeDiff:"2Hora 5m",
        returnTime: "12:25 PM",
      },
      {
        flightNo: "OL5391",
        departTime: "6:55 PM",
        timeDiff:"2Hora 5m",
        returnTime: "9:00 PM",
      },
    ],
  },
  {
    from: 7,
    to: 8,
    days1: [0,1, 3, 5],
    price1: 225.8,
    days2: [2, 4, 6],
    price2: 225.8,
    flights: [
      {
        flightNo: "OL5153",
        departTime: "11:00 AM",
        timeDiff:"1Hora 30m",
        returnTime: "12:30 PM",
      },
      {
        flightNo: "OL5391",
        departTime: "5:50 PM",
        timeDiff:"1Hora 30m",
        returnTime: "7:20 PM",
      },
    ],
  },
];
